### ISSUE TITLE
Vim - Unknown function: plug# ...

### ISSUE THREAD

**Issue by gp-saurabh** [ErickChacon/dotfiles-ubuntu#1]
Opening a file in vim gives me these errors:

→ vi manage.py
Error detected while processing /home/saurabh/.dotfiles/configuration/.vim/autoload/plug.vim:
line  628:
E126: Missing :endfunction
Error detected while processing /home/saurabh/.vimrc:
line  118:
E117: Unknown function: plug#
line  119:
E117: Unknown function: plug#
line  136:
E117: Unknown function: plug#
line  137:
E117: Unknown function: plug#
line  138:
E117: Unknown function: plug#
line  139:
E117: Unknown function: plug#
line  151:
E117: Unknown function: plug#
line  165:
E117: Unknown function: plug#
line  184:
E117: Unknown function: plug#
line  185:
E117: Unknown function: plug#
line  186:
E117: Unknown function: plug#
line  198:
E117: Unknown function: plug#
line  202:
E117: Unknown function: plug#
line  206:
E117: Unknown function: plug#
line  219:
E117: Unknown function: plug#
line  220:
E117: Unknown function: plug#
line  221:
E117: Unknown function: plug#
line  235:
E117: Unknown function: plug#
line  236:
E117: Unknown function: plug#
line  237:
E117: Unknown function: plug#
line  238:
E117: Unknown function: plug#
line  241:
E117: Unknown function: plug#
line  242:
E117: Unknown function: plug#
line  243:
E117: Unknown function: plug#
line  246:
E117: Unknown function: plug#
line  247:
E117: Unknown function: plug#
line  248:
E117: Unknown function: plug#
line  257:
E117: Unknown function: plug#
line  266:
E117: Unknown function: plug#
line  267:
E117: Unknown function: plug#
line  280:
E117: Unknown function: plug#
line  281:
E117: Unknown function: plug#
line  282:
E117: Unknown function: plug#
line  287:
E117: Unknown function: plug#
line  288:
E117: Unknown function: plug#
line  355:
E117: Unknown function: plug#
line  362:
E117: Unknown function: plug#
line  376:
E117: Unknown function: plug#
line  380:
E117: Unknown function: plug#
line  448:
E117: Unknown function: plug#
line  473:
E117: Unknown function: plug#
line  474:
E117: Unknown function: plug#
line  490:
E117: Unknown function: plug#
line  506:
E117: Unknown function: plug#
line  507:
E117: Unknown function: plug#
line  508:
E117: Unknown function: plug#
line  511:
E117: Unknown function: plug#
line  512:
E117: Unknown function: plug#
line  516:
E117: Unknown function: plug#
line  517:
E117: Unknown function: plug#
line  518:
E117: Unknown function: plug#
Error detected while processing function plug#end[82]..<SNR>2_reorg_rtp:
line    1:
E121: Undefined variable: s:first_rtp
E116: Invalid arguments for function empty(s:first_rtp)
line   21:
E121: Undefined variable: s:first_rtp
E116: Invalid arguments for function empty(s:first_rtp)
Error detected while processing function plug#end:
line   86:
E484: Can't open file /usr/share/vim/vim81/syntax/syntax.vim
Error detected while processing /home/saurabh/.vimrc:
line  527:
E484: Can't open file /usr/share/vim/vim81/syntax/syntax.vim
line  903:
E185: Cannot find color scheme 'gruvbox'
line  917:
E185: Cannot find color scheme 'gruvbox'
Press ENTER or type command to continue

**Comment by ErickChacon** [comment]
Hi, I am not sure what you are doing with the dotfiles. I imagine you are using the nvim folder. Please do not use that configuration with `vi`, use it with `neovim`. Remember to install vim-plug `https://github.com/junegunn/vim-plug` to manage the plugins.

**Comment by gp-saurabh** [comment]
Installing vim-plug solved the error. Thank You

**Comment by gp-saurabh** [comment]
After Installing `vim-plug` & using `:PlugInstall` inside vim solves the above errors, but this `vim81` issue persists

> Here I'm opening `.vimrc` file with `vim`

→ vim .vimrc
Error detected while processing function plug#end:
line   86:
E484: Can't open file /usr/share/vim/vim81/syntax/syntax.vim
Error detected while processing /home/saurabh/.vimrc:
line  527:
E484: Can't open file /usr/share/vim/vim81/syntax/syntax.vim
Press ENTER or type command to continue

**Comment by gp-saurabh** [comment]
I'm not sure if it's the right approach, but I followed this link and it worked:

[this](https://stackoverflow.com/questions/37911896/syntax-vim-file-is-missing)
